server:
  port: 10085
spring:
  application:
    name: crm-auth
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
swagger:
  base-package: com.crm.web.controller
